name: Deploy Website

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure public directory exists
        run: mkdir -p public

      - name: Create project-index.json
        run: |
          echo '["stackmaker.json", "soulo.json", "game-ratings.json"]' > public/project-index.json

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/"  # Assumes your build output is in 'dist' folder
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1  # Removes the 'dist' directory from the path

      - name: Execute post-deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add any commands to run on the server after deployment
            # For example, restart services or clear cache
            echo "Deployment completed at $(date)"
